# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 丶一乂
email: dianyiqe@gmail.com
description: To be continued
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://doublehelix.xyz" # the base hostname & protocol for your site
github_username:  dianyiqe

# Build settings
markdown: kramdown
